from machine import Pin
import time

def all(pin1,pin2,pin3):
	led1 = Pin(pin1, Pin.OUT)
	led2 = Pin(pin2, Pin.OUT)
	led3 = Pin(pin3, Pin.OUT)
	time.sleep(2)
	for i in range(10):
			led1.value(0)
			led2.value(1)
			led3.value(1)
			print('led1')
			time.sleep(.25)
			led1.value(1)
			led2.value(0)
			led3.value(1)
			print('led2')
			time.sleep(.25)
			led1.value(1)
			led2.value(1)
			led3.value(0)
			print('led3')
			time.sleep(1)
			led3.value(1)
			print('led33')
			time.sleep(.25)
			led2.value(1)
			print('led22')
			time.sleep(.25)
			led1.value(1)
			print('led11')
			time.sleep(.25)
			for i in range(5):
				time.sleep(.1)
				led2.value(0)
				time.sleep(.1)
				led2.value(1)

#all(0,4,5)